### PR TITLE
Add a download tool which is named hd

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by bacongobbler** [comment]
Most distributions already have a tool called `hd` (hexdump) as part of the standard library. How do we reconcile that?

https://man7.org/linux/man-pages/man1/hexdump.1.html

See `man hd` for more details.

**Comment by LinuxSuRen** [comment]
Thanks for the reminder. I'm wondering if it's possible to give it an alias name. For instance, the original binary name still is `hd`, and install it as `ghd`.

`ghd` means GitHub Download.

**Comment by arbourd** [comment]
For these kind of personal-ish tools, I would recommend using your own rig. I do that for my stuff:
https://github.com/arbourd/rig

**Comment by LinuxSuRen** [comment]
Thanks for your suggestion @arbourd

**Comment by bacongobbler** [comment]
Yeah... This may be better hosted from a personal rig, especially since the name conflicts with existing coreutils.

Thanks.

**Pull request closed without merging**
