### PR TITLE
feat(Food): add fish food for porter

### PR DESCRIPTION
**Pull request by vdice**
Adds fish food for [porter](https://github.com/deislabs/porter)

Looking good when testing on my Mac:
```
 $ gofish install --log-level 9001 porter
==> Installing porter...
🐠  porter v0.3.0-ralpha.1+caipirinha: installed in 21.070885695s
```

### CODE REVIEW

**Comment by vdice** [comment]
cc @carolynvs to double-check/advise on metadata (description, etc.) and binary destinations

**Comment by bacongobbler** [comment]
holding out on merging for now; let me know if you'd like me to merge this one in once you're ready to ship. Thanks!

**Comment by carolynvs** [comment]
Porter doesn't work without any mixins. We don't have the commands (yet) to install mixins, e.g. `porter mixin install helm`, so the install script for porter installs the mixins it needs automatically. I suggest that for now, until we have those commands, the fish food for porter also downloads the mixins. I wouldn't make separate fish food for the mixins since porter will very soon handle getting them itself.

**Comment by vdice** [comment]
Chatted with @bacongobbler on this today.  Currently, there's no desirable way to also fetch associated/dependency binaries for a fish-food script without adding support in this tool.  I think the best course of action, since it's been stated above that porter itself will soon handle fetching these dependencies, is to close this PR and re-open once we can point to the first 'fully-functional'/standalone porter binary (that has the ability to init/fetch mixins).

**Pull request closed without merging**
