### PR TITLE
Update draft.lua to version 0.16.0

### PR DESCRIPTION
**Pull request by yosbeleg89**
Version 0.16.0 of Draft was realeased, please update it to be able to install it using GoFish.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Looks like the windows checksum verification failed: https://ci.appveyor.com/project/bacongobbler/fish-food/build/171

Mind taking a look into that? Thanks!

**Comment by yosbeleg89** [comment]
@bacongobbler it looks like they are linking the wrong sha256 and wrong version in the releases page, I updated now to the correct one :+1:

**Comment by bacongobbler** [comment]
I just noticed that and fixed the typo. I'm one of the Draft maintainers ;)

Thanks!

**Comment by yosbeleg89** [comment]
Nice! :) Thank you!

**Pull request merged**
