### PR TITLE
gomplate: upgrade to 3.7.0

### PR DESCRIPTION
**Pull request by hairyhenderson**
https://github.com/hairyhenderson/gomplate/releases/tag/v3.7.0

### CODE REVIEW

**Comment by bacongobbler** [comment]
hi @hairyhenderson. CI is noticing there's a checksum mismatch failure here. Please make sure the correct shasums are being used. Have a look at the CI failure for more info. Thanks!

**Comment by hairyhenderson** [comment]
@bacongobbler 🤦‍♂️ thanks - I'll have a look... feels like this happened last time too 😅

**Comment by hairyhenderson** [comment]
Hrm... This is a bit confusing:

```console
$ curl -SLO https://github.com/hairyhenderson/gomplate/releases/download/v3.7.0/gomplate_linux-amd64-slim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0   3553      0 --:--:-- --:--:-- --:--:--  3553
100 7867k  100 7867k    0     0  1499k      0  0:00:05  0:00:05 --:--:-- 1677k
$ sha256sum gomplate_linux-amd64-slim
edeafbade658f4cf8dde853b7b2d8b8441936587bded5d32444efee3d3be9b87  gomplate_linux-amd64-slim
```

That's what's expected, but CI is failing with:

```
!!! shasum verify check failed: checksums differ for /root/.gofish/gomplate-3.7.0-linux-amd64: expected 'edeafbade658f4cf8dde853b7b2d8b8441936587bded5d32444efee3d3be9b87', got '4c63639e61ecaeab122c4a5de91d3ea3dcf0100b78ad797cb6e952a01665372f'
```

I'll force-push and trigger CI again 🤷‍♂️

**Comment by hairyhenderson** [comment]
@bacongobbler so `gomplate` is building fine in CI, but looks like `skaffold` is failing now?

```
🐠  No errors discovered in 'gomplate'
==> Installing gomplate...
🐠  gomplate 3.7.0: installed in 32.20968ms
```

...

```
!!! shasum verify check failed: checksums differ for /root/.gofish/skaffold-1.10.0-windows-amd64.exe: expected '3d66a199dfd01b268eb97ce1c6dff9f96bbf2de8213cbaa859d04e489bbdda8d', got '3efa3ddd7b9ba6f4d2d8a3adbba5eaa6c0b5ec98845fdcc0a26144cdf3a06d0e'
!!! shasum verify check failed: checksums differ for /root/.gofish/skaffold-1.10.0-darwin-amd64: expected 'd85bb6c28357cb60b0c609593d70c04567bda09fdf932cda3b9aab52e1784407', got '9f08dcf1382ec6b006a1ee3273d9d4c9fd2ae1e28265c1f46105e0a85e6f5d4a'
Error: 2 errors encountered while linting skaffold
```

I'll force-push again to trigger CI and see if it'll build 🤔

**Comment by hairyhenderson** [comment]
Ok, the last CI also failed due to a `skaffold` checksum mismatch:

```
!!! shasum verify check failed: checksums differ for /root/.gofish/skaffold-1.10.0-windows-amd64.exe: expected '3d66a199dfd01b268eb97ce1c6dff9f96bbf2de8213cbaa859d04e489bbdda8d', got 'd647c511e23ba87c02809b718916c26f992b3fb48f5873ee276df7178a3cccdd'
!!! shasum verify check failed: checksums differ for /root/.gofish/skaffold-1.10.0-darwin-amd64: expected 'd85bb6c28357cb60b0c609593d70c04567bda09fdf932cda3b9aab52e1784407', got '547bfc10e263e02f23849e57115cf4c51e90a9ee84a2d5f3fe854895c48127e0'
Error: 2 errors encountered while linting skaffold
```

**Comment by hairyhenderson** [comment]
(also, oddly, those checksums are _different_)

**Comment by hairyhenderson** [comment]
Ah - the binaries were actually replaced, and so the checksum mismatch was caused by https://github.com/GoogleContainerTools/skaffold/issues/4234

In the meantime they've released https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.10.1 - I'll issue a PR to bump that so this one can build clean 😉

**Comment by hairyhenderson** [comment]
#744 should fix the CI issue here

**Comment by bacongobbler** [comment]
I’ve restarted the job now that #744 has been merged, though it might fail since it probably needs to be rebased first.

If you wouldn’t mind rebasing on top of master, we can verify this PR once more before merging. Thank you!

**Pull request merged**
